"""
core/data_loader.py
===================
Centralised, cache-aware data loading for the Calm Octopuses application.

All functions that read from disk are decorated with ``@st.cache_resource`` so
they are executed at most once per Streamlit session and their return values are
held by reference (no re-serialisation on each rerun).

Key constants
-------------
LOOKUP_CSV, REVIEWS_CSV, IMAGES_CSV, MENUS_JSON, BIOS_JSON
    Primary data files. Note that CSVs were recently moved to ``data/csv/``
    to separate them from raw JSON extracts.
EMBEDDINGS_JSONL, MENU_EMBEDDINGS_JSONL, REVIEW_EMBEDDINGS_JSONL
    CLIP vector files. The loader automatically looks for ``*_latest.jsonl`` 
    versions which are typically generated by pipelines but gitignored.
"""
import json
from pathlib import Path
from typing import Any, Dict, List, Optional
import numpy as np
import pandas as pd
import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
LOOKUP_CSV = DATA_DIR / "csv" / "restaurant_lookup.csv"
MICHELIN_AWARDS_CSV = DATA_DIR / "csv" / "michelin_awards.csv"
MICHELIN_AWARDS_XLSX = DATA_DIR / "csv" / "nyc_michelin_awards.xlsx"
REVIEWS_CSV = DATA_DIR / "csv" / "social_reviews.csv"
IMAGES_CSV = DATA_DIR / "csv" / "social_images.csv"
SENTIMENT_CSV = DATA_DIR / "csv" / "restaurant_profiles.csv"
MENUS_JSON = DATA_DIR / "extracted_menus" / "final_parsed_menus.json"
BIOS_JSON = DATA_DIR / "extracted_bios" / "restaurant_bios_joinable.json"
DEFAULT_CLIP_MODEL_ID = "openai/clip-vit-base-patch32"


def _resolve_embedding_path(filename: str) -> Path:
    """
    Resolve an embeddings file path, falling back to the local ``*_latest`` export.

    This keeps the app compatible with both the canonical filenames used in code
    and the locally generated data exports that are intentionally gitignored.
    """
    default_path = DATA_DIR / "embeddings" / filename
    if default_path.exists():
        return default_path

    if filename.endswith(".jsonl"):
        latest_path = default_path.with_name(f"{default_path.stem}_latest{default_path.suffix}")
        if latest_path.exists():
            return latest_path

    return default_path


EMBEDDINGS_JSONL = _resolve_embedding_path("restaurant_profiles.jsonl")
MENU_EMBEDDINGS_JSONL = _resolve_embedding_path("menu_embeddings.jsonl")
REVIEW_EMBEDDINGS_JSONL = _resolve_embedding_path("review_embeddings.jsonl")
FOOD_EMBEDDINGS_JSONL = _resolve_embedding_path("image_embeddings_food.jsonl")
INTERIOR_EMBEDDINGS_JSONL = _resolve_embedding_path("image_embeddings_interior.jsonl")

def _clean_text(value: Any) -> str:
    """Normalise a raw field value to a single-line, whitespace-collapsed string."""
    if value is None:
        return ""
    return " ".join(str(value).replace("\n", " ").split())

def _truncate(text: str, limit: int = 220) -> str:
    """Return *text* truncated to *limit* characters, adding an ellipsis if necessary."""
    text = _clean_text(text)
    if len(text) <= limit:
        return text
    return text[: limit - 3].rstrip() + "..."

def _load_json_records(path: Path) -> List[Dict[str, Any]]:
    """
    Load a JSON file and return its contents as a flat list of dicts.

    Accepts both top-level arrays and objects whose values are arrays
    under common keys (``records``, ``items``, ``data``, ``results``).
    Returns an empty list if the file does not exist.
    """
    if not path.exists():
        return []

    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)

    if isinstance(data, list):
        return [row for row in data if isinstance(row, dict)]

    if isinstance(data, dict):
        for key in ("records", "items", "data", "results"):
            value = data.get(key)
            if isinstance(value, list):
                return [row for row in value if isinstance(row, dict)]

    return []

def _load_csv(path: Path) -> pd.DataFrame:
    """Load a CSV into a string-typed DataFrame; return an empty DataFrame if the file is missing."""
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path, dtype=str, keep_default_na=False).fillna("")

def _name_key(value: Any) -> str:
    """Return a compact restaurant-name key for joining source files without IDs."""
    return "".join(ch for ch in _clean_text(value).lower() if ch.isalnum())

def _read_awards_xlsx(path: Path) -> pd.DataFrame:
    """Read the current Michelin awards workbook and normalize it to app columns."""
    if not path.exists():
        return pd.DataFrame()

    awards_df = pd.read_excel(path, sheet_name="All Restaurants", dtype=str).fillna("")
    if awards_df.empty:
        return pd.DataFrame()

    lookup_df = _load_csv(LOOKUP_CSV)
    lookup_by_name = {}
    if not lookup_df.empty:
        for row in lookup_df.to_dict(orient="records"):
            key = _name_key(row.get("name"))
            if key:
                lookup_by_name[key] = _clean_text(row.get("rest_id"))

    normalized_rows: List[Dict[str, Any]] = []
    for row in awards_df.to_dict(orient="records"):
        name = _clean_text(row.get("Restaurant Name"))
        original_name = _clean_text(row.get("Original Name in Uploaded Base"))
        rest_id = ""
        for candidate_name in (name, original_name):
            rest_id = lookup_by_name.get(_name_key(candidate_name), "")
            if rest_id:
                break

        try:
            star_count = int(float(row.get("Star Count", 0) or 0))
        except (TypeError, ValueError):
            star_count = 0

        distinction = _clean_text(row.get("Michelin Distinction"))
        if star_count > 0:
            award = f"{star_count} Michelin Star" + ("s" if star_count != 1 else "")
        elif distinction.lower() == "bib gourmand":
            award = "Bib Gourmand"
        else:
            award = distinction

        normalized_rows.append(
            {
                "rest_id": rest_id,
                "restaurant_name": name,
                "michelin_stars": star_count,
                "michelin_award": award,
                "michelin_distinction": distinction,
                "michelin_cuisine": _clean_text(row.get("Cuisine")),
                "michelin_location": _clean_text(row.get("Location / Neighborhood")),
                "michelin_city_area": _clean_text(row.get("City / Area")),
                "michelin_source_url": _clean_text(row.get("Source URL")),
            }
        )

    return pd.DataFrame(normalized_rows)

@st.cache_data(show_spinner=False)
def load_lookup_df() -> pd.DataFrame:
    """Return the restaurant lookup table (``restaurant_lookup.csv``) as a cached DataFrame."""
    return _load_csv(LOOKUP_CSV)

@st.cache_data(show_spinner=False)
def load_michelin_awards_df() -> pd.DataFrame:
    """Return Michelin star/distinction metadata keyed by restaurant id."""
    csv_df = _load_csv(MICHELIN_AWARDS_CSV)
    if not csv_df.empty:
        return csv_df
    return _read_awards_xlsx(MICHELIN_AWARDS_XLSX)

@st.cache_data(show_spinner=False)
def load_reviews_df() -> pd.DataFrame:
    """Return the social reviews CSV as a cached DataFrame."""
    return _load_csv(REVIEWS_CSV)

@st.cache_data(show_spinner=False)
def load_images_df() -> pd.DataFrame:
    """Return the social images CSV as a cached DataFrame."""
    return _load_csv(IMAGES_CSV)

@st.cache_data(show_spinner=False)
def load_menus_df() -> pd.DataFrame:
    """Return the parsed menu records as a cached DataFrame."""
    rows = _load_json_records(MENUS_JSON)
    return pd.DataFrame(rows)

@st.cache_data(show_spinner=False)
def load_sentiment_df() -> pd.DataFrame:
    """Return the sentiment profiles as a cached DataFrame indexed by restaurant_id."""
    if not SENTIMENT_CSV.exists():
        return pd.DataFrame()
    return pd.read_csv(SENTIMENT_CSV).set_index("restaurant_id")

@st.cache_data(show_spinner=False)
def load_bios_df() -> pd.DataFrame:
    """Return the restaurant biography records as a cached DataFrame."""
    rows = _load_json_records(BIOS_JSON)
    if not rows:
        return pd.DataFrame()

    flattened: List[Dict[str, Any]] = []
    for row in rows:
        bio = row.get("bio", {})
        if isinstance(bio, dict):
            bio_text = " ".join(
                _clean_text(bio.get(field)) for field in ("description", "culinary_style", "history")
            ).strip()
        else:
            bio_text = _clean_text(bio)

        flattened.append(
            {
                "rest_id": _clean_text(row.get("rest_id")),
                "restaurant_name": _clean_text(row.get("name")),
                "bio_text": bio_text,
                "match_source": _clean_text(row.get("match_source")),
            }
        )

    return pd.DataFrame(flattened)

@st.cache_resource(show_spinner=False)
def load_restaurant_embeddings() -> Dict[str, np.ndarray]:
    """
    Load the 512-D CLIP restaurant profile embeddings from disk.

    Reads ``data/embeddings/restaurant_profiles.jsonl``.  Each line is a JSON
    object with ``restaurant_id`` (or ``rest_id``) and ``vector`` keys.
    The result is stored via ``@st.cache_resource`` so the large numpy dict
    is kept in memory and never re-hashed between Streamlit reruns.

    Returns
    -------
    dict[str, np.ndarray]
        Mapping of ``rest_id`` to a float32 array of shape (512,).
    """
    if not EMBEDDINGS_JSONL.exists():
        return {}

    embeddings: Dict[str, np.ndarray] = {}
    with EMBEDDINGS_JSONL.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                data = json.loads(line)
                rest_id = _clean_text(data.get("restaurant_id", data.get("rest_id")))
                vector = data.get("vector")
                if rest_id and vector:
                    embeddings[rest_id] = np.array(vector, dtype=np.float32)
            except json.JSONDecodeError:
                continue

    return embeddings

@st.cache_resource(show_spinner=False)
def load_finegrained_embeddings(file_path_str: str) -> Dict[str, List[np.ndarray]]:
    """
    Load per-item CLIP embeddings from a JSONL file (menu or review).

    Unlike ``load_restaurant_embeddings``, a single restaurant can have multiple
    vectors (one per dish or review).  The result is a dict mapping each
    ``rest_id`` to a list of float32 arrays.

    Parameters
    ----------
    file_path_str : str
        Absolute path to the JSONL file.  Pass ``str(MENU_EMBEDDINGS_JSONL)``
        or ``str(REVIEW_EMBEDDINGS_JSONL)`` from the module constants.

    Returns
    -------
    dict[str, list[np.ndarray]]
        Mapping of ``rest_id`` to a list of shape-(512,) float32 arrays.
    """
    file_path = Path(file_path_str)
    if not file_path.exists():
        return {}
        
    embeddings = {}
    with file_path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line: continue
            try:
                data = json.loads(line)
                rest_id = _clean_text(data.get("restaurant_id", data.get("rest_id")))
                vector = data.get("vector")
                if rest_id and vector:
                    if rest_id not in embeddings:
                        embeddings[rest_id] = []
                    embeddings[rest_id].append(np.array(vector, dtype=np.float32))
            except json.JSONDecodeError:
                continue
    return embeddings

def _resolve_path(path_value: str) -> Path:
    """Resolve *path_value* to an absolute ``Path``, anchoring relative paths at the project root."""
    path = Path(_clean_text(path_value))
    if path.is_absolute():
        return path
    return PROJECT_ROOT / path

def _first_existing_path(paths: List[str]) -> Optional[str]:
    """
    Return the first path in *paths* that exists on disk, or the first path as a fallback.

    Used to locate the best representative image for a restaurant when multiple
    candidate paths are stored in the catalog.
    """
    for raw_path in paths:
        candidate = _resolve_path(raw_path)
        if candidate.exists():
            return str(candidate)
    return str(_resolve_path(paths[0])) if paths else None

def _join_snippets(values: List[str], limit: int = 6) -> str:
    """Join up to *limit* cleaned string values with a single space for search indexing."""
    snippets = [_clean_text(value) for value in values if _clean_text(value)]
    return " ".join(snippets[:limit]).strip()

def _extract_menu_items(menu_rows: List[Dict[str, Any]], limit: int = 6) -> List[str]:
    """
    Format up to *limit* menu rows into human-readable "dish - ingredients - $price" strings.
    """
    items: List[str] = []
    for row in menu_rows[:limit]:
        dish = _clean_text(row.get("dish_name"))
        ingredients = _clean_text(row.get("ingredients"))
        price = _clean_text(row.get("price"))
        parts = [part for part in [dish, ingredients, f"${price}" if price else ""] if part]
        if parts:
            items.append(" - ".join(parts))
    return items

def _extract_review_snippets(review_rows: List[Dict[str, Any]], limit: int = 4) -> List[str]:
    """Extract up to *limit* review text snippets, annotating each with its star rating."""
    snippets: List[str] = []
    for row in review_rows[:limit]:
        text = _clean_text(row.get("text"))
        rating = _clean_text(row.get("rating"))
        if text:
            snippets.append(f"{text} {'(' + rating + ' stars)' if rating else ''}".strip())
    return snippets

@st.cache_resource(show_spinner=False)
def build_restaurant_catalog() -> pd.DataFrame:
    """
    Builds and returns the fully joined restaurant catalog as a cached resource.

    Joins the lookup table with menus, reviews, images, and bios to produce
    a single wide DataFrame with one row per restaurant.  Pre-computed fields
    include ``search_text`` (for CLIP query matching), ``menu_items``,
    ``review_snippets``, ``image_paths``, and boolean coverage flags.

    Decorated with ``@st.cache_resource`` (not ``@st.cache_data``) so that the
    large, list-typed DataFrame is held by reference rather than being
    pickled and re-hashed on every Streamlit rerun — which was the primary
    cause of frontend startup lag.

    Returns an empty DataFrame if the lookup CSV is missing.
    """
    # Cache buster: 2
    lookup_df = load_lookup_df()
    awards_df = load_michelin_awards_df()
    reviews_df = load_reviews_df()
    images_df = load_images_df()
    menus_df = load_menus_df()
    bios_df = load_bios_df()
    if lookup_df.empty:
        return pd.DataFrame()

    lookup_records = lookup_df.to_dict(orient="records")
    lookup_records.sort(key=lambda row: _clean_text(row.get("name")).lower())

    bio_map: Dict[str, str] = {}
    if not bios_df.empty:
        for row in bios_df.to_dict(orient="records"):
            rest_id = _clean_text(row.get("rest_id"))
            if not rest_id:
                continue
            bio_map[rest_id] = _clean_text(row.get("bio_text"))

    award_map: Dict[str, Dict[str, Any]] = {}
    if not awards_df.empty:
        for row in awards_df.to_dict(orient="records"):
            rest_id = _clean_text(row.get("rest_id"))
            if rest_id:
                award_map[rest_id] = row

    records: List[Dict[str, Any]] = []
    menu_groups = menus_df.groupby("rest_id") if not menus_df.empty and "rest_id" in menus_df.columns else None
    review_groups = reviews_df.groupby("rest_id") if not reviews_df.empty and "rest_id" in reviews_df.columns else None
    image_groups = images_df.groupby("rest_id") if not images_df.empty and "rest_id" in images_df.columns else None

    for row in lookup_records:
        rest_id = _clean_text(row.get("rest_id"))
        if not rest_id:
            continue

        menu_rows = menu_groups.get_group(rest_id).to_dict(orient="records") if menu_groups is not None and rest_id in menu_groups.groups else []
        review_rows = review_groups.get_group(rest_id).to_dict(orient="records") if review_groups is not None and rest_id in review_groups.groups else []
        image_rows = image_groups.get_group(rest_id).to_dict(orient="records") if image_groups is not None and rest_id in image_groups.groups else []

        image_paths = [_clean_text(image_row.get("image_path")) for image_row in image_rows if _clean_text(image_row.get("image_path"))]
        representative_image_path = _first_existing_path(image_paths)

        menu_items = _extract_menu_items(menu_rows)
        review_snippets = _extract_review_snippets(review_rows)
        bio_text = bio_map.get(rest_id, "")
        award_row = award_map.get(rest_id, {})
        try:
            michelin_stars = int(float(award_row.get("michelin_stars", 0) or 0))
        except (TypeError, ValueError):
            michelin_stars = 0
        michelin_award = _clean_text(award_row.get("michelin_award")) or (
            f"{michelin_stars} Michelin Star" + ("s" if michelin_stars != 1 else "")
            if michelin_stars
            else _clean_text(row.get("michelin_category"))
        )

        search_text = " ".join(
            [
                _clean_text(row.get("name")),
                _clean_text(row.get("borough")),
                _clean_text(row.get("michelin_category")),
                bio_text,
                _join_snippets(menu_items),
                _join_snippets(review_snippets),
            ]
        ).strip()

        records.append(
            {
                "rest_id": rest_id,
                "restaurant_name": _clean_text(row.get("name")),
                "homepage": _clean_text(row.get("homepage")),
                "borough": _clean_text(row.get("borough")),
                "michelin_category": _clean_text(row.get("michelin_category")),
                "michelin_stars": michelin_stars,
                "michelin_award": michelin_award,
                "michelin_distinction": _clean_text(award_row.get("michelin_distinction")),
                "michelin_cuisine": _clean_text(award_row.get("michelin_cuisine")),
                "michelin_location": _clean_text(award_row.get("michelin_location")),
                "bio_text": bio_text,
                "menu_items": menu_items,
                "review_snippets": review_snippets,
                "image_paths": image_paths,
                "representative_image_path": representative_image_path,
                "menu_count": len(menu_rows),
                "review_count": len(review_rows),
                "image_count": len(image_paths),
                "has_menu": bool(menu_rows),
                "has_reviews": bool(review_rows),
                "has_food_images": bool(image_paths),
                "search_text": search_text,
            }
        )

    return pd.DataFrame(records)
